### ISSUE TITLE
Help checking case studies from field epidemiology training programmes

### ISSUE THREAD

**Issue by aspina7** [RECON-gathering-March-2018/projects#8]
Graduates from field epidemiology training programmes have translated some data analysis case studies in to R. 

It would be really great if some advanced users could check the scripts to make sure it is as good as possible so that it could then be released to the wider community and used as templates for teaching R data analysis for outbreaks!

**Comment by mhoehle** [comment]
This sounds like a nice idea. Is the material available online somewhere? Not sure this is possible, but putting the code on github, then one way would be to comment/improve using pull requests?

**Comment by aspina7** [comment]
Yep was thinking the same - will try and get some pushed on to github by tomorrow so can share!
