### ISSUE TITLE
Making RECON-learn more navigable for Epis

### ISSUE THREAD

**Issue by aspina7** [RECON-gathering-March-2018/projects#9]
[RECON-learn](https://reconlearn.netlify.com/) is a really useful tool for starting to learn R specifically for epidemiology. 

It would be great if it was easier to look up specific examples of data analyses more easily. 

Sort of in the style of [UCLA IDRE](https://stats.idre.ucla.edu/other/dae/), [R graph gallery](https://www.r-graph-gallery.com/) or [RExRepos](http://dwoll.de/rexrepos/index.html)

**Comment by thibautjombart** [comment]
Yep yep, indeed. We are contracting Steph Locke to reform the website, but it is taking time :-/ 
The wish list is there:
https://github.com/reconhub/learn/issues/7

Feel free to add to it!
